---
# SSSD is ready to use on RHEL 7 major_release >=7 or major_release=6 + release >=6.6 otherwise skip it
#
- block:
  # Install default packages list
  - include: "{{ ansible_pkg_mgr }}.yml"
  - include: ldap.yml
  - include: services.yml
  - include: sshd.yml
  when: (ansible_os_family == 'RedHat' and ansible_distribution_version | version_compare('6.6', '>=' ))  or ( ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8 )
# Debian Wheezy ssh version don't support get ssh key on ldap add cron job to manually update them : 
- include: manual_ssh_key.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version|int == 7

